### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username=hodolman&password=1234&remember=1

### 메인 페이지

GET http://localhost:8080

### 인증 페이지 요청

GET http://localhost:8080/foo
Content-Type: application/json
Cookie: SESSION=65a45a88-b6e2-4d62-886b-ad5112d71072