### 회원가입

POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "호돌맨",
  "email": "hodolman88@gmail.com",
  "password": "1234"
}

### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username=hodolman88@gmail.com&password=1234&remember=1

### 메인 페이지

GET http://localhost:8080

### 사용자 페이지

GET http://localhost:8080/user

### 관리자 페이지

GET http://localhost:8080/admin

### 인증 페이지 요청

GET http://localhost:8080/foo
Content-Type: application/json
Cookie: SESSION=65a45a88-b6e2-4d62-886b-ad5112d71072